# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "renum"
  s.version = "1.4.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["John Hume"]
  s.date = "2013-03-16"
  s.description = "provides a readable but terse enum facility for Ruby"
  s.email = "duelin.markers@gmail.com"
  s.extra_rdoc_files = [
    "README.textile"
  ]
  s.files = [
    ".travis.yml",
    "Gemfile",
    "Gemfile.lock",
    "README.textile",
    "Rakefile",
    "VERSION",
    "lib/renum.rb",
    "lib/renum/enumerated_value.rb",
    "lib/renum/enumerated_value_type_factory.rb",
    "lib/renum/index_serializer.rb",
    "lib/renum/name_serializer.rb",
    "renum.gemspec",
    "spec/renum_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/duelinmarkers/renum"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.15"
  s.summary = "provides a readable but terse enum facility for Ruby"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rake>, [">= 0"])
      s.add_development_dependency(%q<rspec>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
    else
      s.add_dependency(%q<rake>, [">= 0"])
      s.add_dependency(%q<rspec>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
    end
  else
    s.add_dependency(%q<rake>, [">= 0"])
    s.add_dependency(%q<rspec>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
  end
end

